# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = binutils_intro
SUB_SRC_FILES = \
    preface.xml \
    ch01_gnu_binutils_intro.xml \
    ch02_ld.xml \
    ch03_as.xml \
    ch04_addr2line.xml \
    ch05_ar.xml \
    ch06_cpp_filt.xml \
    ch07_dlltool.xml \
    ch08_gold.xml \
    ch09_gprof.xml \
    ch010_nlmconv.xml \
    ch011_nm.xml \
    ch012_objcopy.xml \
    ch013_objdump.xml \
    ch014_ranlib.xml \
    ch015_readelf.xml \
    ch016_size.xml \
    ch017_strings.xml \
    ch018_strip.xml \
    ch019_windmc.xml \
    ch020_windres.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk